### ISSUE TITLE
Fix webpack copyDirectory directives

### ISSUE THREAD

**Issue by jonathanbossenger** [jonathanbossenger/devdadjokes#12]
On the initial implementation of the new front end from #11, the asset-building process did not seem to be working properly.

@szhabolcs was kind enough to point out that the `purge` configuration in the `tailwind.config.js` was incorrect, which I then [updated](https://github.com/jonathanbossenger/devdadjokes/commit/546783494323de4a15014997ca219b8c6e36b784#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2eR1) based on the tailwind docs

However now, the `copyDirectory` commands in the `webpack.mix.js` don't seem to be happening

https://github.com/jonathanbossenger/devdadjokes/blob/main/webpack.mix.js

```
.copyDirectory('resources/css/themes', 'public/css/themes')
.copyDirectory('resources/img', 'public/img');
```

And so it does not appear to copy over the `themes` and the `img` directories after `npm run prod` is run.

**Comment by rosswintle** [comment]
Can you paste in some command line output to see what Mix/Webpack is doing?

Also, can you confirm your node/npm versions?

**Comment by rosswintle** [comment]
I ran a quick test with your repo and it was fine on node v12.20.0 and npm v6.14.8

```
$ ls public/img
dev-icon.svg    github-icon.svg

$ ls resources/img
dev-icon.svg    github-icon.svg

$ ls public/css/themes
mac    ubuntu win

$ ls resources/css/themes
mac    ubuntu win
```

npm complained about a major update though so will try with a more up-to-date node and see what happens.

**Comment by rosswintle** [comment]
All seems fine here with node v15.5.0 and npm v7.3.0 too. Strange.

**Comment by jonathanbossenger** [comment]
@rosswintle ok thanks. I've been having an issue with the production deployment of the app, using the Digital Ocean App Platform, so that might be why. I have to run `npm run prod` manually. 

Thanks for testing/confirming it all works as it should, it's my first time working with Tailwind.

**Comment by rosswintle** [comment]
OK. Cool. I've not tested a DO deploy. On my local copy the only issue I had was that I hadn't set up an HTTPS cert and you are forcing HTTPS in `app/Providers/AppServiceProvider.php`.

Once I sorted that out I had a working local copy. So the build process itself - the layers of Tailwind, PostCSS, Mix, Webpack - are all working fine.

So must be something odd with your DO deployment.

**Comment by jonathanbossenger** [comment]
@rosswintle yeah, I originally had some http/https mixed content warnings, so I added that to try and work around it. Must remove that, because it seems fine now.

That's what was weird to me, Laravel Mix was building successfully, but on the last deploy, it didn't seem to copy those files. However, your second test helps me confirm the issue is with the deployment, not the config. Thanks very much for testing!

**Comment by rosswintle** [comment]
As you're using the `asset()` helped you should be able to fix that by setting `APP_URL` in the `.env`

Hope you get the deploy figured out!

**Comment by jonathanbossenger** [comment]
> As you're using the `asset()` helped you should be able to fix that by setting `APP_URL` in the `.env`

Yeah, that was the first thing I did, but the app platform didn't accept it (or so it appeared) until the next time I deployed. May have just been a caching thing though...

**Comment by assertchris** [comment]
Did you link the storage on the production server?
