### ISSUE TITLE
Fix export and share button styling on smaller screens

### ISSUE THREAD

**Issue by jonathanbossenger** [jonathanbossenger/devdadjokes#20]
@szhabolcs 

I implemented an export and share button on the app this weekend. Export stores the image to jpeg to be saved, the share will (eventually) upload that image to Twitter and create a new Tweet for the user.

![Dev_Dad_Jokes](https://user-images.githubusercontent.com/180629/111112220-73c02f80-8568-11eb-8dfa-4eada02cee10.png)

As you can see, on narrow screens, the share button is not responsive, this is probably because I just copied the share button to make the export button.

No rush, but If you have some time to look into this and drop a CSS fix here, I would greatly appreciate it. 

Thanks

**Comment by szhabolcs** [comment]
@jonathanbossenger duplicate of #17

**Comment by jonathanbossenger** [comment]
@szhabolcs ahahahahaha ok thanks. Will close this one.
