### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by szhabolcs** [jonathanbossenger/devdadjokes#21]
@jonathanbossenger I made a logo, hope you like it! 😄 
![new logo](https://user-images.githubusercontent.com/54114237/111120393-f4385d80-8573-11eb-93a5-510f80739a5f.png)
(updated positioning)

**Comment by jonathanbossenger** [comment]
Those look awesome! 😍

Please feel free to PR them into a location that's suitable, and I'll update the Twitter account!

**Comment by jonathanbossenger** [comment]
One small thing I just realised.

Is there any way to make the "Dad Jokes" font the same size?

I'll tell you why, I don't want the name to look like it's for "dads" only. The name is based on the concept of the (dad joke)[https://en.wikipedia.org/wiki/Dad_joke] but I fear that giving the font size focus on the 'dev dad' part makes it look like it's for devs and dads (therefore male) only.

**Comment by szhabolcs** [comment]
@jonathanbossenger  I've done some new mockups. The wide one is a twitter banner 😄
![new logos](https://user-images.githubusercontent.com/54114237/111158540-cddce700-85a0-11eb-89c5-1505560ac7e6.png)

I also made these, but they don't feel as good as the one above:
![other tries at logo](https://user-images.githubusercontent.com/54114237/111158673-fcf35880-85a0-11eb-9329-cf3946dd16bc.png)

**Comment by jonathanbossenger** [comment]
💪🎉😍 Very cool mate! Yes, I agree, the first ones look awesome. Nice work!

**Comment by jonathanbossenger** [comment]
Fixed by #22
